### ISSUE TITLE
Evil bindings for guix.el released!

### ISSUE THREAD

**Issue by Ambrevar** [alezost/guix.el#17]
Just to let you know: I've just added support for `guix.el` to [Evil Collection](https://github.com/emacs-evil/evil-collection).

Comments are welcome!

@alezost: It was a good opportunity to explore the various features of `guix.el` a bit more in depth: I'm amazed by how rich and polished the user experience is.  You've done a fantastic job here!

**Comment by alezost** [comment]
> Just to let you know: I've just added support for guix.el to Evil Collection.

Thank you!  I will add a mention about it in README.

> Comments are welcome!

I am not an evil user, so I don't have comments, but I see that you invest a lot of time in studying emacs-guix facilities :-)

> It was a good opportunity to explore the various features of guix.el a bit more in depth: I'm amazed by how rich and polished the user experience is. You've done a fantastic job here!

He-he, thank you, although I don't really do much on emacs-guix these days.

**Comment by alezost** [comment]
I think this can be closed, as it is not an issue.  Thank you for making these evil key bindings!
