### ISSUE TITLE
C-c C-z (switch-to-geiser) does not work

### ISSUE THREAD

**Issue by Ambrevar** [alezost/guix.el#19]
From a Scheme buffer in Guix mode:

- `M-x guix-switch-to-repl`
; Point is not in the Guix REPL.
- `M-x switch-to-geiser`
; Does nothing.

Is there a way to go back to the calling buffer?

**Comment by alezost** [comment]
> From a Scheme buffer in Guix mode:

Do you mean `guix-devel-mode`?  If so, note that this minor mode is not related to `Guix REPL` at all!  It just provides several commands additionally to the Geiser functionality (look at [the manual section](https://alezost.github.io/guix.el/manual/latest/html_node/Development.html#Development) for details).  So in a scheme buffer you just use a general Geiser workflow with some additional stuff (font-lock highlighting and commands) from `guix-devel-mode`.

> - M-x guix-switch-to-repl
>   ; Point is not in the Guix REPL.

Do you mean the point **is** in the Guix REPL (or **is not**)?  Note that the Guix REPL is not used by any scheme buffer in any way!  It is used to display packages, generations, etc. and to do some operations that are performed from the `*Guix ...` buffers (to install packages, to switch/delete generations, etc.).

> Is there a way to go back to the calling buffer?

Yes, just use `M-x switch-to-geiser` from the calling buffer, not `M-x guix-switch-to-repl`.

**Comment by alezost** [comment]
Closing this.  @Ambrevar let me know if something is still not clear

**Comment by Ambrevar** [comment]
Sorry, forgot to go back to this: yes, this makes perfect sense, I got confused by my Scheme setup!
