### ISSUE TITLE
a checked out guix

### ISSUE THREAD

**Issue by humanitiesNerd** [alezost/guix.el#2]
Say I have a foder with a checked ot guix master branch in it

Manually, I use to cd into that folder, then call

```
.pre-ins-env guix ... blah blah
.pre-ins-env guile ... blah blah

```
I'd like the manual to give an example of how to configure the `guix-guile-program` variable in order to have Emacs-Guix using the guix/guile from within that folder as I do manually

Thanks

**Comment by alezost** [comment]
Do you mean you want to have the following line to be added to the manual:

```elisp
(setq guix-guile-program '("/path/to/guix-checkout/pre-inst-env" "guile"))
```

right?

To be honest, I've never tried this method and I don't know how
reliable it is, but it should work in theory.

**Comment by alezost** [comment]
@humanitiesNerd, since you didn't reply I made what seemed appropriate to me as you can see at:

https://alezost.github.io/guix.el/manual/latest/html_node/Guile-and-Build-Options.html#Guile-and-Build-Options

Let me know, if there is something else you had in mind.

**Comment by humanitiesNerd** [comment]
2017-06-19 20:56 GMT+02:00 Alex Kost <notifications@github.com>:

> @humanitiesNerd <https://github.com/humanitiesnerd>, since you didn't
> reply I made what seemed appropriate to me as you can see at:
>
> https://alezost.github.io/guix.el/manual/latest/html_
> node/Guile-and-Build-Options.html#Guile-and-Build-Options
>
> Let me know, if there is something else you had in mind
>

Sorry for not replying, I was distracted and somewat overwhelmed with
things

I'd say it's ok.

Thank you !
