### ISSUE TITLE
org-mode Scheme source code block collides with guix-devel-code-block-edit

### ISSUE THREAD

**Issue by wigust** [alezost/guix.el#22]
Hello Alex,

Before a new `emacs-guix` release, I want to discus a `org-mode` Scheme source code block:
```
#+BEGIN_SRC scheme

#+END_SRC
```

`C-c '` inside this source code block will invoke a new buffer and window.  After finishing typing a code, I assume to close it with `C-c '`, but instead I get a message `user-error: The point should be inside ’description’ or ’synopsis’`.

So, `guix-devel-code-block-edit` collide with a default well known by users `org-mode` behavior.  Could we bind `guix-devel-code-block-edit` to another key?

**Comment by alezost** [comment]
> Could we bind guix-devel-code-block-edit to another key?

Sure, what about putting it to the same prefix as the other commands, I mean `C-c . '`?

**Comment by alezost** [comment]
Great, done by commit ad1f928135a61bcd44e59c85b30fdaab80906989, thanks!
