### ISSUE TITLE
Move to Gitlab

### ISSUE THREAD

**Issue by Ambrevar** [alezost/guix.el#25]
I see there is a new website and a Gitlab repo:
- https://emacs-guix.gitlab.io/website/
- https://gitlab.com/emacs-guix/emacs-guix

Planning on moving there permanently?
If so, instead of creating a new repository on GitLab, you should "import" this repository on GitHub so that all issues and pull requests get copied along.

Also don't forget to redirect from the GitHub repo and to update the MELPA recipe :)

**Comment by alezost** [comment]
> Planning on moving there permanently?

No, I plan to keep all the repos (on github, gitlab and notabug) :-)

It is probably not what people usually do, but I have been done this for a couple of years (it's just the website that moved to gitlab recently), so I think there shouldn't be any problem.

Some people hate github (especially after Microsoft), some probably don't like "small" hosts like notabug, so you have a freedom to use a platform you prefer.

**Comment by Ambrevar** [comment]
I see, thanks for clarifying that! :)
