### ISSUE TITLE
Issues with "size" command

### ISSUE THREAD

**Issue by Ambrevar** [alezost/guix.el#27]
When the package is not installed `guix.el` should warn the user appropriately.  Instead it returns:
- no result in text mode,
- "no file ... found" in image mode.

When the package is installed, image mode fails with:
```
guix-geiser-eval: Error in evaluating guile expression: guix/scripts/size.scm:202:4: In procedure profile->page-map:
error: make-page-map: unbound variable
```

**Comment by alezost** [comment]
Sorry, I don't reproduce; it works perfectly for me.  This error comes from guix itself.  Does `guix size ...` work for you?

**Comment by alezost** [comment]
I think it happens because of the same problems that we discuss on guix-help list

**Comment by Ambrevar** [comment]
No, this is is different, I haven't set the `geiser-guile-load-path` this time and other transactions work.
`guix size ...` also fails from command-line and I figured it's because `guile-charting` is not installed.  It's actually mentioned in the manual, my bad.
That said, the issue with the bad feedback when the package is not installed remains.

**Comment by alezost** [comment]
It should work when the package is not installed.  Do you still have `~/projects/guix` on the top of `%load-path` (I replied to your message on guix-help several minutes ago)?  I think it can effect.

**Comment by Ambrevar** [comment]
Hmm... I think it only works when substitutes are available for the package.

**Comment by alezost** [comment]
When substitutes are unavailable, I see:

    guix size: error: no available substitute information for ...

in the Guix REPL.  Otherwise (with substitutes), the repl shows the size output.  Is it the same for you?

**Comment by alezost** [comment]
> I see that now in text mode, but previously there was nothing (see my first post).

OK, if it works now, then I think nothing can be done here.

> In image mode there still is an error about a file that is not found.

Right, this happens because the file was not created (because of the substitute error).  The error message can be improved though.  What about the following:

    Couldn't create an image file.
    Please check "guix size" shell command to make sure it works.

**Comment by Ambrevar** [comment]
If I get it right, there can be only 2 errors:
- no substitute
- guile-charting missing
Can we detect that and output the corresponding error message?

**Comment by alezost** [comment]
I think there may be other errors (like any "guix" command fails :smile:).  Anyway, parsing an error just for this simple message seems too complicated for me.  I think a reference to "guix size" should be OK.

**Comment by Ambrevar** [comment]
Alright! :)

**Comment by alezost** [comment]
Done in commit f220e82b2dd94fb349ae37665912a42196d53975

Thanks!
