### ISSUE TITLE
guix-devel: generate a shell command string which used to build current "define-public"

### ISSUE THREAD

**Issue by tumashu** [alezost/guix.el#3]
I want to a command, which can generate a command string, for example: "guix build -f /temp/path/emacs-exwm-x.scm  emacs-exwm-x", so I can use this command to build package current be edited

**Comment by tumashu** [comment]
the role thing is that: how to generate a valid emacs-exwm-x.scm ...

**Comment by alezost** [comment]
Sorry, I don't understand: do you want to generate some file with a package or to generate some command to build a package from that file?

**Comment by tumashu** [comment]
generate a file contain current package and  build it in a terminal emulator

**Comment by alezost** [comment]
OK, since I don't have a need and interest in this feature, I'm not
going to implement it, sorry.  But I leave this issue open.  Perhaps
someone will do it some day :wink:

**Comment by tumashu** [comment]
The below is my hack, if it is useful, I will send a pull-request.

```
(defun guix-export-package ()
    (interactive)
    (let* ((directory (file-name-as-directory guix-export-directory))
           (current-module (guix-guile-current-module))
           (define-public-string
             (save-excursion
               (end-of-defun)
               (let ((end (point)))
                 (beginning-of-defun)
                 (buffer-substring (point) end))))
           (package-name
            (progn (string-match "\\(define-public +\\)\\([a-z-]+\\)\n+"
                                 define-public-string)
                   (match-string 2 define-public-string)))
           (define-module-string
             (replace-regexp-in-string
              " *(define-module.*\n"
              (format (concat "(define-module (%s)\n"
                              "  #:use-module %s\n")
                      package-name current-module)
              (save-excursion
                (goto-char (point-min))
                (search-forward "(define-module")
                (end-of-defun)
                (let ((end (point)))
                  (beginning-of-defun)
                  (buffer-substring (point) end)))))
           (command (format "guix package --load-path='%s' -i %s "
                            directory package-name)))
      (unless (file-directory-p directory)
        (make-directory directory t))
      (with-temp-buffer
        (insert define-module-string)
        (insert "\n")
        (insert define-public-string)
        (write-file (concat directory package-name ".scm"))
        (kill-new command)
        (message command)))
```

**Comment by alezost** [comment]
To be honest, this looks too hacky and specialized only for your needs.  I don't think it can be useful for anyone but you.

On the other hand, if you make it more general, I will accept it.  By "more general" I mainly mean the "guix package -i ..." command.  It should be customizable (for example, one may want to use "guix build ..." instead), i.e. there should be a variable with this guix command.

So if you still have a wish to make a pull request, I will write some more comments.

I hope the above didn't sound rude :smile:

**Comment by tumashu** [comment]
```
this looks too hacky 
```
you mean the way "define-public to file" is too hacky?

**Comment by alezost** [comment]
I mean this is highly specific for your needs, and I believe it is unlikely it may be useful for anyone else.

You already have a file with a package, then you make another file with the same package just to feed it to "guix" command.  This really seems unnatural to me, sorry

**Comment by tumashu** [comment]
OK
