### ISSUE TITLE
`find-newest-available-packages` disappeared

### ISSUE THREAD

**Issue by civodul** [alezost/guix.el#30]
Hello,

I removed `find-newest-available-packages` from `(gnu packages)` in Guix commit e2a903c807ccacec5925f197ce26f626060e1953 (Jan. 2019) because it was not used internally.  Only recently did I realize that Emacs-Guix uses it.

Would it be an option for you to re-introduce it in `packages.scm` in Emacs-Guix proper?  WDYT?

Apologies for the breakage!

**Comment by civodul** [comment]
In the meantime I've reintroduced the procedure in Guix commit f2bf0407de70e7ae29518400d66ef968134f5169.

**Comment by alezost** [comment]
Hello!  I did not expect to meet you on github :-) In case you didn't
know, Emacs-Guix also exists on notabug:
<https://notabug.org/alezost/emacs-guix>.  You may open issues there or
send me a direct email if it is more convenient for you.

To be honest, I would gladly remove `M-x guix-newest-packages` from
Emacs-Guix, as it is almost the same as `M-x guix-all-packages`.  So
please remove `find-newest-available-packages` again if Guix does not
need it.  And I will remove the according command from Emacs-Guix.  I
think people will not miss it.

**Comment by civodul** [comment]
Hi Alex!

> Hello!  I did not expect to meet you on github :-) In case you didn't
> know, Emacs-Guix also exists on notabug:
> <https://notabug.org/alezost/emacs-guix>.  You may open issues there or
> send me a direct email if it is more convenient for you.

Oh thanks for letting me know!

> To be honest, I would gladly remove `M-x guix-newest-packages` from
> Emacs-Guix, as it is almost the same as `M-x guix-all-packages`.  So
> please remove `find-newest-available-packages` again if Guix does not
> need it.  And I will remove the according command from Emacs-Guix.  I
> think people will not miss it.

I agree.  :-)

Ludo’.

**Comment by alezost** [comment]
>> To be honest, I would gladly remove `M-x guix-newest-packages` from
>> Emacs-Guix, as it is almost the same as `M-x guix-all-packages`. So
>> please remove `find-newest-available-packages` again if Guix does  not
>> need it. And I will remove the according command from Emacs-Guix. I
>> think people will not miss it.
>
> I agree. :-)
>
> Ludo’.

OK, great, so `M-x guix-newest-packages` will be removed in the next
Emacs-Guix release, thanks!
