### ISSUE TITLE
Minor problem of a command being shadowed in the shell guix commands subpopup

### ISSUE THREAD

**Issue by Zzull** [alezost/guix.el#32]
The letter 'u' seems to be bound for both the `publish` and the `upgrade` actions

![2019-05-12-210306_89x60_scrot](https://user-images.githubusercontent.com/1597334/57586691-d9b97700-74f9-11e9-985c-5b4348197b82.png)

**Comment by alezost** [comment]
I guess you meant in `M-x guix-command`.  If so, it was fixed in master: <https://github.com/alezost/guix.el/commit/03ec17838bd9871ed398d587d777613209056697>.

Thanks.

**Comment by Zzull** [comment]
Many thanks
