### ISSUE TITLE
Only Small Subset of Pacakges Appear on GuixSD

### ISSUE THREAD

**Issue by ecbrown** [alezost/guix.el#35]
With an up-to-date GuixSD, I do not see all (10,000+) packages, but rather only a small subset (~790).  I seem to recall it showing all packages the first time I ran it.

Using guix-installed emacs on Debian GNU/Linux buster, I see all 10,000+ pacakges.

**Comment by alezost** [comment]
Perhaps there is some problem with modules. Are there any
errors/warnings in `*Guix REPL*` buffer?  Could you please show
the output of `%load-path` and `%load-compiled-path`.

Oh, BTW, do you use channels?

**Comment by ecbrown** [comment]
Weird, same problem now in Debian Buster + Guix. Not using channels on this machine.

scheme@(emacs-guix)> %load-path
$4 = ("/home/ebrown/src/guix" "/gnu/store/mvm6b330h1v1564v28kdl8qzi2dvxwxs-emacs-guix-0.5.1.1/share/guile/site/2.2" "/home/ebrown/.config/guix/current/share/guile/site/2.2" "/gnu/store/hxc9gknc6gfhx96b0ak0d6r3pv4mhayv-guix-1.0.1-5.cc98b00/share/guile/site/2.2" "/gnu/store/q62w3wc35nyhjvr4bcqy563wkqx0c425-emacs-geiser-0.10/share/geiser/guile/" "~/src/guix" "/home/ebrown/.guix-profile/share/guile/site/2.2" "/gnu/store/9alic3caqhay3h8mx4iihpmyj6ymqpcx-guile-2.2.4/share/guile/2.2" "/gnu/store/9alic3caqhay3h8mx4iihpmyj6ymqpcx-guile-2.2.4/share/guile/site/2.2" "/gnu/store/9alic3caqhay3h8mx4iihpmyj6ymqpcx-guile-2.2.4/share/guile/site" "/gnu/store/9alic3caqhay3h8mx4iihpmyj6ymqpcx-guile-2.2.4/share/guile")

scheme@(emacs-guix)> %load-compiled-path
$5 = ("/home/ebrown/src/guix" "/gnu/store/mvm6b330h1v1564v28kdl8qzi2dvxwxs-emacs-guix-0.5.1.1/lib/guile/2.2/site-ccache" "/home/ebrown/.config/guix/current/lib/guile/2.2/site-ccache" "/gnu/store/hxc9gknc6gfhx96b0ak0d6r3pv4mhayv-guix-1.0.1-5.cc98b00/lib/guile/2.2/site-ccache" "/home/ebrown/.guix-profile/lib/guile/2.2/site-ccache" "/gnu/store/9alic3caqhay3h8mx4iihpmyj6ymqpcx-guile-2.2.4/lib/guile/2.2/ccache" "/gnu/store/9alic3caqhay3h8mx4iihpmyj6ymqpcx-guile-2.2.4/lib/guile/2.2/site-ccache")

**Comment by alezost** [comment]
I see that "/home/ebrown/src/guix" has the priority over the other paths (you probably added it to `guix-load-path` variable).  I guess it is the directory with guix source. Do you keep it up-to-date and built (with `make`)?  If not, it should better be removed from the path.

**Comment by ecbrown** [comment]
I think you’ve discovered the issue! I ensured that the guix source code was built, and 11,000+ packages appeared!

Will check on my GuixSD machine ASAP and close the issue once I’ve confirmed that this is solved.
