### ISSUE TITLE
`guix package --list-profiles`?

### ISSUE THREAD

**Issue by zimoun** [alezost/guix.el#36]
Dear,

If I read well, the profiles are provided by [this piece of code](https://github.com/alezost/guix.el/blob/master/elisp/guix-ui-profile.el#L45-L55) (`defcustom`) and then listed by [this piece of code](https://github.com/alezost/guix.el/blob/master/elisp/guix-ui-profile.el#L357-L360) (`defun`).

Now there is an CLI to list all the user's profile: `guix package --list-profiles`.

I am not sure to have my mind clear enough: using this new Guix plumbing, is it better to update the variable `guix-profile`  or the function?

Thank you in advance.
All the best

**Comment by alezost** [comment]
Sorry for the long delay, I rarely check issues :blush:

I didn't know about `guix package --list-profiles`, thank you for
letting me know!  I will surely update Emacs-Guix to find all the
profiles.  Hopefully, it will happen soon enough :smile:.

**Comment by zimoun** [comment]
> Sorry for the long delay, I rarely check issues

Do you preferably check the Github instance or the Gitlab one?


Thank you for working on this.

**Comment by alezost** [comment]
> Do you preferably check the Github instance or the Gitlab one?

I don't have a preference.  The only difference is: Gitlab sends me
e-mails every time a new issue is opened, and Github does it only when
my nickname is mentioned (I mean @alezost).  So most of the times I am
not aware when a new issue is opened on Github.

Anyway, I have just added a support for all profiles (commit 97670a52),
so this feature will appear in the next Emacs-Guix release.  Thank you
for pointing me to this!

**Comment by alezost** [comment]
I have made Emacs-Guix release (version 0.5.2), so it should display all the user profiles now.  Please let me know, if it does not work.

**Comment by zimoun** [comment]
Hi,
Thank you. I will report to you if I experiment issues.
All the best.
