### ISSUE TITLE
Invoking guix-packages by name in empty line fails

### ISSUE THREAD

**Issue by nico202** [alezost/guix.el#45]
when the point is on an empty line, this fails:

https://github.com/alezost/guix.el/blob/8ce6d219e87c5097abff9ce6f1f5a4293cdfcb31/elisp/guix-ui-package.el#L1516

with: `split-string: Wrong type argument: stringp, nil`

something like this should work:
```emacs-lisp
(or (thing-at-point 'symbol t) "")
```

**Comment by alezost** [comment]
Thank you for the report! As you see I rarely check open issues :-)
